version = 0.1

[default.deploy.parameters]
stack_name = "mini-full-stack"
resolve_s3 = true
s3_prefix = "mini-full-stack"
region = "ap-southeast-2"
confirm_changeset = false   # ← 自動承認に変更
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
