AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda → Glue → Athena PoC（自動トリガー対応、RoleNameなし、CAPABILITY_IAMのみ）

Parameters:
  GlueJobName:
    Type: String
    Default: mini-glue-job

Resources:

  # S3 バケット（データアップロード用）
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-input-bucket"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 バケット（Athena 結果用）
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-athena-results"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda 実行用 IAM Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${AWS::StackName}-input-bucket
                  - !Sub arn:aws:s3:::${AWS::StackName}-input-bucket/*
                  - !Sub arn:aws:s3:::${AWS::StackName}-athena-results
                  - !Sub arn:aws:s3:::${AWS::StackName}-athena-results/*
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                Resource: "*"
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

  # Lambda 関数（S3 トリガー付き）
  LambdaGlueAthena:
    Type: AWS::Serverless::Function
    DependsOn:
      - InputBucket          # バケット作成完了後まで待機
      - AthenaResultBucket
      - LambdaExecutionRole  # ロール作成完了後まで待機
    Properties:
      FunctionName: lambda-glue-athena
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          INPUT_BUCKET: !Ref InputBucket
          ATHENA_OUTPUT_BUCKET: !Ref AthenaResultBucket
          GLUE_JOB_NAME: !Ref GlueJobName
          ATHENA_DATABASE: mini_glue_db
      Events:
        OnCsvUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv"

  # Glue Job 用 IAM ロール
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${AWS::StackName}-input-bucket
                  - !Sub arn:aws:s3:::${AWS::StackName}-input-bucket/*
                  - !Sub arn:aws:s3:::${AWS::StackName}-athena-results
                  - !Sub arn:aws:s3:::${AWS::StackName}-athena-results/*

  # Glue Job（ETL 仮置き）
  GlueETLJob:
    Type: AWS::Glue::Job
    DependsOn:
      - InputBucket       # スクリプト格納先バケットが必要
      - GlueJobRole       # Glue Job Role が作成されるまで待機
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${AWS::StackName}-input-bucket/glue-scripts/etl.py"
        PythonVersion: 3
      MaxCapacity: 2

Outputs:
  LambdaFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref LambdaGlueAthena

  InputBucketName:
    Description: "S3 Input Bucket Name"
    Value: !Ref InputBucket

  AthenaResultBucketName:
    Description: "S3 Athena Result Bucket Name"
    Value: !Ref AthenaResultBucket

  GlueJobName:
    Description: "Glue Job Name"
    Value: !Ref GlueETLJob
