AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda → Glue → Athena PoC（固定バケット名、Eventsなし、IAM最小化）

Parameters:
  GlueJobName:
    Type: String
    Default: mini-glue-job

Resources:

  # S3 バケット（データアップロード用）
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mini-full-input
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 バケット（Athena 結果用）
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mini-full-output
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda 実行用 IAM Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::mini-full-input
                  - arn:aws:s3:::mini-full-input/*
                  - arn:aws:s3:::mini-full-output
                  - arn:aws:s3:::mini-full-output/*
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobName}
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

  # Lambda 関数（Eventsなし）
  LambdaGlueAthena:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-glue-athena
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          INPUT_BUCKET: !Ref InputBucket
          ATHENA_OUTPUT_BUCKET: !Ref AthenaResultBucket
          GLUE_JOB_NAME: !Ref GlueJobName
          ATHENA_DATABASE: mini_glue_db

  # Lambda Invoke Permission（S3からの呼び出し許可）
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaGlueAthena
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt InputBucket.Arn

  # Glue Job 用 IAM ロール
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::mini-full-input
                  - arn:aws:s3:::mini-full-input/*
                  - arn:aws:s3:::mini-full-output
                  - arn:aws:s3:::mini-full-output/*

  # Glue Job（ETL 仮置き）
  GlueETLJob:
    Type: AWS::Glue::Job
    DependsOn: GlueJobRole
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://mini-full-input/glue-scripts/etl.py
        PythonVersion: 3
      MaxCapacity: 2

Outputs:
  LambdaFunction:
    Description: Lambda Function Name
    Value: !Ref LambdaGlueAthena
  InputBucketName:
    Description: S3 Input Bucket Name
    Value: !Ref InputBucket
  AthenaResultBucketName:
    Description: S3 Athena Result Bucket Name
    Value: !Ref AthenaResultBucket
  GlueJob:
    Description: Glue Job Name
    Value: !Ref GlueETLJob
