AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda PoC (循環依存解消版)

Resources:

  # S3 バケット
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mini-full-stack
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda 関数
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Policies:
        - S3ReadPolicy:
            BucketName: mini-full-stack
      Environment:
        Variables:
          BUCKET_NAME: mini-full-stack
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events: s3:ObjectCreated:*

Outputs:
  LambdaFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref MyLambda

  S3BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref MyBucket
