AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda → Glue → Athena PoC (S3トリガー手動設定版)

Parameters:
  GlueJobName:
    Type: String
    Default: mini-glue-job

Resources:

  # S3 バケット（データアップロード用）
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mini-full-stack
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 バケット（Athena 結果用）
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mini-athena-results
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda 実行用 IAM Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-glue-athena-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 読み書き
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::mini-full-stack
                  - !Sub arn:aws:s3:::mini-full-stack/*
                  - !Sub arn:aws:s3:::mini-athena-results
                  - !Sub arn:aws:s3:::mini-athena-results/*
              # Glue Job 実行
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                Resource: "*"
              # Athena クエリ実行
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

  # Lambda 関数（S3トリガーは手動設定）
  LambdaGlueAthena:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-glue-athena
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          INPUT_BUCKET: !Ref InputBucket
          ATHENA_OUTPUT_BUCKET: !Ref AthenaResultBucket
          GLUE_JOB_NAME: !Ref GlueJobName
          ATHENA_DATABASE: mini_glue_db
      # Events を削除して手動設定に変更

  # Glue Job（ETL 仮置き）
  GlueETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://mini-full-stack/glue-scripts/etl.py
        PythonVersion: 3
      MaxCapacity: 2

  # Glue Job 用 IAM ロール
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::mini-full-stack
                  - !Sub arn:aws:s3:::mini-full-stack/*
                  - !Sub arn:aws:s3:::mini-athena-results
                  - !Sub arn:aws:s3:::mini-athena-results/*

Outputs:
  LambdaFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref LambdaGlueAthena

  InputBucketName:
    Description: "S3 Input Bucket Name"
    Value: !Ref InputBucket

  AthenaResultBucketName:
    Description: "S3 Athena Result Bucket Name"
    Value: !Ref AthenaResultBucket

  GlueJobName:
    Description: "Glue Job Name"
    Value: !Ref GlueETLJob
