AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda → Glue → Athena PoC（依存関係・IAM最小化）

Parameters:
  GlueJobName:
    Type: String
    Default: mini-glue-job

Resources:

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-input-bucket"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-athena-results"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${InputBucket}
                  - !Sub arn:aws:s3:::${InputBucket}/*
                  - !Sub arn:aws:s3:::${AthenaResultBucket}
                  - !Sub arn:aws:s3:::${AthenaResultBucket}/*
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${GlueJobName}
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"

  LambdaGlueAthena:
    Type: AWS::Serverless::Function
    DependsOn: InputBucket
    Properties:
      FunctionName: lambda-glue-athena
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          INPUT_BUCKET: !Ref InputBucket
          ATHENA_OUTPUT_BUCKET: !Ref AthenaResultBucket
          GLUE_JOB_NAME: !Ref GlueJobName
          ATHENA_DATABASE: mini_glue_db
      Events:
        OnCsvUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv"

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${InputBucket}
                  - !Sub arn:aws:s3:::${InputBucket}/*
                  - !Sub arn:aws:s3:::${AthenaResultBucket}
                  - !Sub arn:aws:s3:::${AthenaResultBucket}/*

  GlueETLJob:
    Type: AWS::Glue::Job
    DependsOn: GlueJobRole
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${AWS::StackName}-input-bucket/glue-scripts/etl.py"
        PythonVersion: 3
      MaxCapacity: 2

Outputs:
  LambdaFunction:
    Description: Lambda Function Name
    Value: !Ref LambdaGlueAthena
  InputBucketName:
    Description: S3 Input Bucket Name
    Value: !Ref InputBucket
  AthenaResultBucketName:
    Description: S3 Athena Result Bucket Name
    Value: !Ref AthenaResultBucket
  GlueJob:
    Description: Glue Job Name
    Value: !Ref GlueETLJob
