name: Deploy SAM

on:
  push:
    branches: [ master ]   # master ブランチへの push で実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. AWS 認証情報を設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # 3. SAM CLI をセットアップ
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      # 4. （任意）リポジトリルートのディレクトリ構造を確認
      - name: List repository files
        run: ls -R

      # 5. SAM ビルド
      - name: Build SAM application
        run: sam build --template-file mini_full_stack/template.yaml

      # 6. SAM デプロイ
      - name: Deploy SAM stack
        run: sam deploy \
              --template-file mini_full_stack/template.yaml \
              --stack-name my-stack \
              --capabilities CAPABILITY_IAM \
              --no-confirm-changeset
